-- ============================================================
-- KJY Inventory Cloud App - Supabase Database Schema
-- ร้านคำเจริญเกษตรยนต์ (Kamjarenkasetyon)
-- ============================================================

-- 1. Create EXTENSIONS if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. PROFILES TABLE (User roles: 'owner' or 'staff')
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'staff' CHECK (role IN ('owner', 'staff')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
        COALESCE(NEW.raw_user_meta_data->>'role', 'staff')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 3. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE,
    name TEXT NOT NULL,
    category TEXT,
    cost_price NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
    sale_price NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
    stock_qty INT DEFAULT 0 NOT NULL,
    front_stock INT DEFAULT 0 NOT NULL,
    warehouse_stock INT DEFAULT 0 NOT NULL,
    location_code TEXT,
    image_url TEXT,
    location_image_url TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'pending', 'archived')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast real-time search
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products (name);
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products (sku);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (category);
CREATE INDEX IF NOT EXISTS idx_products_location ON public.products (location_code);


-- 4. LOCATIONS TABLE (โกดัง / ชั้นวาง)
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 5. PURCHASE RECEIPTS TABLE (บิลสั่งซื้อ)
CREATE TABLE IF NOT EXISTS public.purchase_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no TEXT,
    supplier_name TEXT,
    receipt_date DATE DEFAULT CURRENT_DATE,
    total_amount NUMERIC(12, 2) DEFAULT 0.00,
    image_url TEXT,
    ocr_raw_json JSONB,
    ocr_status TEXT DEFAULT 'pending' CHECK (ocr_status IN ('pending', 'completed', 'failed')),
    created_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 6. RECEIPT ITEMS TABLE (รายการในบิล)
CREATE TABLE IF NOT EXISTS public.receipt_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT REFERENCES public.purchase_receipts(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    ocr_name TEXT NOT NULL,
    qty INT DEFAULT 1 NOT NULL,
    unit_cost NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
    line_total NUMERIC(12, 2) GENERATED ALWAYS AS (qty * unit_cost) STORED,
    match_status TEXT DEFAULT 'matched' CHECK (match_status IN ('matched', 'new_product', 'pending')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 7. COST HISTORY TABLE (ประวัติต้นทุนสินค้า)
CREATE TABLE IF NOT EXISTS public.cost_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    receipt_id BIGINT REFERENCES public.purchase_receipts(id) ON DELETE SET NULL,
    old_cost NUMERIC(12, 2) DEFAULT 0.00,
    new_cost NUMERIC(12, 2) NOT NULL,
    changed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cost_history ENABLE ROW LEVEL SECURITY;

-- Helper Function to check if current user is owner
CREATE OR REPLACE FUNCTION public.is_owner()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'owner'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by authenticated users" 
    ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can update own profile" 
    ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Products Policies
CREATE POLICY "Authenticated users can read products" 
    ON public.products FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert products" 
    ON public.products FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update products" 
    ON public.products FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Owner can delete products" 
    ON public.products FOR DELETE TO authenticated USING (public.is_owner());

-- Purchase Receipts Policies
CREATE POLICY "Authenticated users can select receipts"
    ON public.purchase_receipts FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert receipts"
    ON public.purchase_receipts FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Owner can update receipts"
    ON public.purchase_receipts FOR UPDATE TO authenticated USING (public.is_owner());

-- Cost History Policies (Owner Only)
CREATE POLICY "Owner can access cost history"
    ON public.cost_history FOR ALL TO authenticated USING (public.is_owner());


-- ============================================================
-- SUPABASE STORAGE BUCKET SETUP ('kjy-images')
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('kjy-images', 'kjy-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'kjy-images'
CREATE POLICY "Public Read Access for kjy-images"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'kjy-images');

CREATE POLICY "Authenticated Upload Access for kjy-images"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'kjy-images');

CREATE POLICY "Authenticated Update Access for kjy-images"
    ON storage.objects FOR UPDATE TO authenticated
    USING (bucket_id = 'kjy-images');

CREATE POLICY "Authenticated Delete Access for kjy-images"
    ON storage.objects FOR DELETE TO authenticated
    USING (bucket_id = 'kjy-images');
