-- ============================================================
-- KJY Inventory - Migration 002: Add missing columns to products
-- ไปรันใน Supabase SQL Editor (https://supabase.com/dashboard)
-- Idempotent: รันซ้ำได้ปลอดภัย
-- ============================================================

-- 1. Add description column (TEXT)
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';

-- 2. Add min_stock column (INTEGER DEFAULT 5)
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS min_stock INT DEFAULT 5 NOT NULL;

-- 3. Add location column (TEXT) - ข้อความตำแหน่งจัดเก็บเพิ่มเติม
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '';

-- 4. Add audit_log table (ถ้ายังไม่มี)
CREATE TABLE IF NOT EXISTS public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    action_type TEXT NOT NULL,
    description TEXT,
    performed_by TEXT DEFAULT 'staff',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Enable RLS on audit_log
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- 6. Allow authenticated users to insert audit logs
CREATE POLICY "Authenticated users can insert audit logs" 
    ON public.audit_log FOR INSERT TO authenticated WITH CHECK (true);

-- 7. Allow authenticated users to read audit logs
CREATE POLICY "Authenticated users can read audit logs" 
    ON public.audit_log FOR SELECT TO authenticated USING (true);

-- ============================================================
-- Verify: check columns now exist
-- ============================================================
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'products' 
ORDER BY ordinal_position;